{{- if .Values.autoscaling.enabled }}
apiVersion: {{ .Values.autoscaling.apiVersion }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "sqs-to-sns.fullname" . }}
  labels:
    {{- include "sqs-to-sns.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "sqs-to-sns.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  {{- if eq .Values.autoscaling.apiVersion "autoscaling/v1" }}
  targetCPUUtilizationPercentage: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
  {{- else }}
  {{- /*
    defaults to autoscaling/v2
  */}}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
        type: Utilization
  {{- end }}
{{- end }}
